Optimize requests for repository
release-engineering/ubi-population-tool pull request #153
Opened 2021-06-30 10:09 UTC by rbikar

Previously ubipop requested repository from pulp
in every iteration in _create_srpms_output_set method.
Let's save the repository into dict in order not to do
unnecesary requests to pulp.

2021-06-30 13:28 UTC, nathanegillett approved these changes

2021-07-01 03:31 UTC, rohanpm requested changes

2021-07-01 03:31 UTC, rohanpm commented on ubipop/__init__.py
> +                in_repo.id, in_repo.get_source_repository()
Hmm... I'm not entirely sure this works as you intended.

If we have this:

```
somedict.setdefault(somekey, expr)
```

The expression `expr` is evaluated every time even if the value ends up being unused.  So that means we're still calling get_source_repository the same number of times we were before.

If in_repo.get_source_repository() returns future then this probably still speeds up the code, since the function isn't blocking; but it would be doing pointless requests in the background, creating futures which are never used.  That might have some negative performance impact too because those requests do make use of the limited number of request threads for querying Pulp, so it might delay later operations on the client.

We probably just need to use a boring old 'if' statement here.

2021-07-01 06:19 UTC, rbikar commented on ubipop/__init__.py
> +                in_repo.id, in_repo.get_source_repository()
hmm, ok. I thought that setdefault immediately returns value, if the key exists.

2021-07-01 21:43 UTC, rohanpm commented on ubipop/__init__.py
> +                in_repo.id, in_repo.get_source_repository()
Well it's just a plain function.  If you imagine you implemented a function:

```python
def my_fn(a, b):
    # ...

# called like this:
my_fn(1+2, 3+4)
```

Is there any code you can write inside of my_fn which can reach "upwards" and cause (3+4) not to be evaluated?

No, it's too late by that point, python had to calculate a value for your function's arguments before your function could be called.

2021-07-01 21:43 UTC, rohanpm approved these changes

2021-07-21 11:33 UTC, merged