ubipop indicate user populating a repo without ubi_config_version [RHELDST-8053]
release-engineering/ubi-population-tool pull request #173
Opened 2021-10-09 06:00 UTC by dichen16

Check if ubi_config_version note info exists before calling _get_config(),
so it will not crash when ubi_config_version is empty.
And an ERROR level logger added.

2021-10-11 11:19 UTC, dichen16 commented
@rbikar @rohanpm 
I don't have any good idea to tackle this coverage issue. So I think it's ready for a review, or do you have any suggestion about it?

2021-10-19 10:01 UTC, rbikar requested changes
Can you check also PR and commit msg? It says that it will not crash - but actually the code will crash - which is what we want.

2021-11-03 10:44 UTC, rbikar commented
run tests

2021-11-03 10:44 UTC, rbikar commented
> @rbikar Bob, seems my "run tests" comment cannot trigger the Jenkins CI, could you help with that? BTW, ready for review smile

That's weird, trying it myself.

2021-11-03 11:09 UTC, rbikar commented on ubipop/__init__.py
> +    def _get_config(self, yum_repo, config):
Minor: adding 'yum_' prefix is probably not needed, just 'repo' would be fine.

2021-11-22 07:47 UTC, rbikar commented
@dichen16  Can you rebase in upstream master branch? I've just merged fix for unit tests.

2021-11-22 08:03 UTC, dichen16 commented
run tests

2021-11-22 08:05 UTC, dichen16 commented
@rbikar my "run tests" did not work still, and re-request review.

2021-11-22 08:14 UTC, rbikar commented
run tests

2021-11-22 08:14 UTC, rbikar commented
@dichen16  I checked config of the github setting on jenkins, it looks you are not in "admins list", so your "run tests" are ignored.

2021-11-22 08:54 UTC, rbikar approved these changes

2021-11-22 11:00 UTC, merged