Refactor the ubipop test cases
release-engineering/ubi-population-tool pull request #187
Opened 2022-06-22 16:12 UTC by LinglingXiang

1.use the manifest to do the ubipop
2.use the gitlab as the config url
3.add some validation for the check
4.add the expected json result
5.add one test case only, the next will be added later

2022-06-23 13:07 UTC, rbikar requested changes

2022-06-23 13:07 UTC, rbikar commented on tests/integration/test_association.py
> +    # verify the module exist in the repo
can you be more precise with terminology on this and following lines?
module -> modulemd
module defaults -> modulemd_defaults

2022-06-23 13:07 UTC, rbikar commented on tests/integration/test_association.py
> +        assert get_module_default_from_repo(rpm_repo, [module_name]), "Can't find the module :{}".format(module)
I guess this should report "Can't find the modulemd_defaults"

2022-06-23 13:07 UTC, rbikar commented on tests/integration/test_association.py
> +        assert get_module_from_repo(rpm_repo, [module_name]), "Can't find the module :{}" .format(module)
Will this work accurately?
It's allowed to have more modulemd units with the same name, stream and context, so I believe you need to use and query for modulemd by nsvca, using name is not enough.

2022-06-23 13:07 UTC, rbikar commented on tests/integration/test_association.py
> +    modules = query_repo_modules(None, "ubi", rpm_rpo_url, full_data=True)
rpm_rpo_url -> rpm_repo_url

2022-06-23 13:23 UTC, rbikar requested changes

2022-06-23 13:23 UTC, rbikar commented on tests/integration/test_association.py
>      res = p.do_request("post", url, {"criteria": criteria})
This can be refactored so with use pubtools.pulplib.Client

2022-06-23 13:23 UTC, rbikar commented on tests/integration/test_association.py
> +    client = make_pulp_client(url="https://"+PULP_HOSTNAME+"/", auth=(PULP_USER, PULP_PWD), insecure=False)
Ideally we should should context manager (with statement) when working with pulp client.
Also this seems to create a new client every time you call this function, can we somehow share client at least in one test case? (Probably using fixture would be the way)

This applies also to other occurrences of the same.

2022-06-23 13:23 UTC, rbikar commented on tests/integration/test_association.py
> +    filename_path = os.path.join(os.getcwd(), "tests/integration/data/ubi8")
a btw the path  "tests/integration/data/ubi8"  doesn't seem to exist in test data dir.

2022-06-23 13:23 UTC, rbikar commented on tests/integration/test_association.py
> +        Criteria.with_field_in("content_type_id", ["modulemd"]),
Criteria.with_field_in is deprecated.
You should use  with_field(field_name, Matcher.in_(field_value))

Applies also for other occurrences.

2022-06-23 13:24 UTC, rbikar commented
Please fix also failure reported by static checks.

2022-06-24 04:02 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    f = open(filename)
ack

2022-06-24 04:02 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    filename_path = os.path.join(os.getcwd(), "tests/integration/data/ubi8")
ack

2022-06-24 04:04 UTC, LinglingXiang commented on tests/integration/test_association.py
> +        # verify the rpm exist in the cdn server
no, it's the check packages in the pulp server's /home/cdn path, as we set the environment cdn server is the same as pulp, so called it cdn

2022-06-24 04:04 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    # verify the module exist in the repo
ack

2022-06-24 04:04 UTC, LinglingXiang commented on tests/integration/test_association.py
> +        assert get_module_default_from_repo(rpm_repo, [module_name]), "Can't find the module :{}".format(module)
ack

2022-06-24 04:04 UTC, LinglingXiang commented on tests/integration/test_association.py
> +        assert get_module_from_repo(rpm_repo, [module_name]), "Can't find the module :{}" .format(module)
ack

2022-06-24 04:04 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    modules = query_repo_modules(None, "ubi", rpm_rpo_url, full_data=True)
ack

2022-06-24 04:04 UTC, LinglingXiang commented on tests/integration/test_association.py
>      res = p.do_request("post", url, {"criteria": criteria})
this is the old method which we can delete directly

2022-06-24 04:05 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    client = make_pulp_client(url="https://"+PULP_HOSTNAME+"/", auth=(PULP_USER, PULP_PWD), insecure=False)
ack

2022-06-24 04:05 UTC, LinglingXiang commented on tests/integration/test_association.py
> +        Criteria.with_field_in("content_type_id", ["modulemd"]),
ack

2022-06-28 10:02 UTC, rbikar requested changes

2022-06-28 10:02 UTC, rbikar commented on tests/integration/test_association.py
> +        file_list = []
Minor: you don't have to  end the name of these variables with _list_.
Instead you can use _files_, _modules_ ...

2022-06-28 10:02 UTC, rbikar commented on tests/integration/test_association.py
> +    Create a tuple consisting of module name and additional module data..
.. -> .

2022-06-29 08:47 UTC, merged