Adding logs and exception for ubi repo sets [RHELDST-11863]
release-engineering/ubi-population-tool pull request #194
Opened 2022-10-31 14:12 UTC by amcmahon-rh

If the debug or source repo for an RPM repo was not present, the returned value was None, which caused an attribute exception since the code would try accessing values from None. This change checks to ensure these repos actually exist, and raises an exception if they're not present.

2022-10-31 14:38 UTC, rbikar commented
run tests

2022-11-01 10:47 UTC, rbikar commented
run tests

2022-11-01 11:29 UTC, rbikar requested changes

2022-11-01 11:29 UTC, rbikar commented on ubipop/__init__.py
> +            if not out_source_repo.result():
Please consider de-duplication of this like:
```
for repo, repo_type in zip([r1, r2], ["source", "debug"]):
...
```

2022-11-01 11:29 UTC, rbikar commented on ubipop/__init__.py
> +                raise RepoMissing()
Missing debug repo is not fatal error, it shouldn't raise exception.
Can also check `UbiRepoSet._ensure_repos_existence()` method? Seems like we check existence for this two times now. Maybe some re-ordering or refactoring of checks can be useful.

2022-11-01 13:15 UTC, amcmahon-rh commented on ubipop/__init__.py
> +                raise RepoMissing()
1. The _get_ubi_repo_sets() function is called in a try/except block. If the repo doesn't exist this exception is caught and the content set is skipped. In fact, when looking at the UbiRepoSet class, if the repo doesn't exist the exception is also raised, that is, if the execution were to carry on, the same exception would be raised already

2. Another approach to this would be to changing _get_population_sources to return None if the input is None and let UbiRepoSet be the one to raise an error. I think the check inside the UbiRepoSet should be left in place, in case the class is used by other routes at some point. Stuff like this makes me miss monads

2022-11-01 13:27 UTC, rbikar commented on ubipop/__init__.py
> +                raise RepoMissing()
The main point of my comment is that missing **debug** repo is not a problem and in this case the processing can continue. At least this was specified when ubi tooling was designed but in practice this never happened.
On the other hand missing **source** repo is a problem and we can't continue.

2022-11-01 13:41 UTC, rbikar commented on ubipop/__init__.py
> +                raise RepoMissing()
I checked briefly newer code and it looks that debug repo is required is some places already.
This is gonna fail, if the debug repo is missing, e.g. `out_repos.debug` is `Future[None]` or something that returns None.
```
        # start async querying for modulemds and modular and non-modular packages
        if self.ubim_client:
            binary_manifest = self.ubim_client.get_manifest(self.repos.out_repos.rpm.id)
            debug_manifest = self.ubim_client.get_manifest(
                self.repos.out_repos.debug.id
            )
```
So I think we could switch to logic where the debug repo is required.

2022-11-01 13:46 UTC, rbikar commented on ubipop/__init__.py
> +                raise RepoMissing()
But I also think we don't want to extend the scope of the issue and improving the logging properly is enough right now.

2022-11-01 14:56 UTC, amcmahon-rh commented on ubipop/__init__.py
> +                raise RepoMissing()
erh, I didn't see this final comment. I've implemented the approach I mentioned in the second point in my previous comment. It prevents the attribute access exception and a lets the UbiRepoSet class take care of checking for existence. I've also changed the debug repo not existing to be "fatal". LMK if this approach makes more sense

2022-11-04 11:20 UTC, rbikar requested changes

2022-11-04 11:20 UTC, rbikar commented on ubipop/__init__.py
> +        if not out_repo:
Unfortunately it looks this part of code is poorly covered by tests (which is not your fault) and in real use it likely won't work as intended because out_repo will be future in cases: `out_source_repo` and `out_debug_repo` . 
I guess `if out_repo.result():` should fix the issue but `out_rpm_repo` has to be made a future sooner that it is now.

Just checked the `get_source_repository()` and  `get_debug_repository()` methods in pubtools-pulplib and they will return either a proxy future returning repo or future returning None, but even then the future is evaluated as True in if statement:
```
>>> from more_executors.futures import f_return
>>> bool(f_return())
True
>>> bool(f_return().result())
False
>>> 
```

2022-11-04 13:24 UTC, amcmahon-rh commented on ubipop/__init__.py
> +        if not out_repo:
would it be possible instead to extend the original check with `hasattr`. So:

`if not hasattr(out_repo, "population_sources") or not out_repo.population_sources`

will produce false for None because the first condition fails, which means the second condition doesn't get evaluated.

2022-11-04 13:42 UTC, rbikar commented on ubipop/__init__.py
> +        if not out_repo:
does `hasattr` work with proxy futures?

2022-11-04 15:52 UTC, amcmahon-rh commented on ubipop/__init__.py
> +        if not out_repo:
It appears to work for proxy futures yes. I've tested it on Ling's QE environment

2022-11-07 07:41 UTC, rbikar commented on ubipop/__init__.py
> +        if not out_repo:
ok, let's try `hasattr` but please make sure it's covered by unit tests.

2022-11-08 09:00 UTC, rbikar commented
codecov will be fixed by https://github.com/release-engineering/ubi-population-tool/pull/195

2022-11-08 10:01 UTC, rbikar commented
run tests

2022-11-10 10:09 UTC, rbikar commented
run tests

2022-11-10 10:58 UTC, rbikar commented
run tests

2022-11-10 13:21 UTC, rbikar commented
run tests

2022-11-14 09:11 UTC, rbikar commented
run tests

2022-11-15 07:36 UTC, rbikar commented
run tests

2022-11-15 09:15 UTC, rbikar approved these changes

2022-11-15 09:15 UTC, merged