Fixup: still dumps exception instead of simple log
release-engineering/ubi-population-tool pull request #198
Opened 2022-11-16 11:57 UTC by amcmahon-rh

The main issue was resolved, in that we were trying to access a value which wasn't present. However, we should return None and allow the UbiRepoSet class to raise a RepoMissing exception,  which is already captured and logged.

2022-11-16 12:00 UTC, amcmahon-rh commented
An alternative approach would be to keep the exception and add PopulationSourceMissing to the caught exceptions. However, allowing the UbiRepoSet class to take care of it will give logs on which repo specifically is missing.

2022-11-23 11:08 UTC, rbikar requested changes

2022-11-23 11:08 UTC, rbikar commented on ubipop/__init__.py
> +            return None
Can you make it return empty list instead so we retutrn the same types in all cases?

2022-11-25 10:06 UTC, amcmahon-rh commented
run tests

2022-11-30 10:38 UTC, rbikar commented
@amcmahon-rh 
Please rebase on current master, there is py27 CI fix.

2022-11-30 10:54 UTC, rbikar approved these changes

2022-11-30 10:54 UTC, merged