Remove Legacy code in ubipop  [RHELDST-13337]
release-engineering/ubi-population-tool pull request #199
Opened 2022-11-17 12:38 UTC by jihupdc

1.Legacy code in ubipop is removed.
2.ubi-manifest is the only source of expected content for ubipop.

2022-11-18 08:53 UTC, rbikar commented
Please check coverage report whether the reported problems are new or if they were not covered previously as well.
Also rebase on current on master, you are currently reverting some change already merged in master.

2022-11-18 08:53 UTC, rbikar requested changes

2022-11-18 08:53 UTC, rbikar commented on ubipop/cli.py
> +    logging.getLogger("pubtools.pulplib").setLevel(logging.INFO)
Why is this in diff? You shouldn't touch that.
Please rebase on master

2022-11-18 08:53 UTC, rbikar commented on ubipop/__init__.py
> +        if not out_repo.population_sources:
This is also unrelated. Please rebase on master.

2022-11-18 08:53 UTC, rbikar commented on .pylintrc
> +        unnecessary-lambda,
Any comment to this?

2022-11-18 11:17 UTC, jihupdc commented on ubipop/__init__.py
> +        if not out_repo.population_sources:
Done

2022-11-23 11:56 UTC, rbikar commented
Please see detailed codecov report https://app.codecov.io/gh/release-engineering/ubi-population-tool/pull/199 and please fix parts of code that are newly not covered by tests.

2022-11-30 10:36 UTC, rbikar requested changes

2022-11-30 10:36 UTC, rbikar commented on ubipop/__init__.py
> +            _LOG.warning("Output Debug repo does not exist")
This seems like you are reverting some changes from master, please check.

2022-11-30 10:37 UTC, rbikar commented
@jihupdc 
Please rebase on master so the py27 tests can pass.

2022-11-30 13:24 UTC, jihupdc commented on ubipop/__init__.py
> +            _LOG.warning("Output Debug repo does not exist")
Done

2022-11-30 14:08 UTC, rbikar requested changes

2022-11-30 14:08 UTC, rbikar commented on ubipop/__init__.py
> +            _LOG.warning("Input Debug repo does not exist")
This also shouldn't be part of this change.

2022-12-01 09:34 UTC, jihupdc commented on ubipop/__init__.py
> +            _LOG.warning("Input Debug repo does not exist")
Done

2022-12-01 10:11 UTC, rbikar commented
@jihupdc 
I think this PR needs another rebase on master to fix the failing test or maybe another fix (ref. https://github.com/release-engineering/ubi-population-tool/pull/198/files )

2022-12-02 10:52 UTC, rbikar requested changes
I believe the removed test case is still relevant and should be kept in place.

2022-12-02 10:52 UTC, rbikar commented on tests/test_ubipop.py
> -def test_get_ubi_repo_sets_repo_missing(
What's the reason for removing this test case?

2022-12-05 10:32 UTC, rbikar commented
run tests

2022-12-05 10:49 UTC, rbikar approved these changes

2022-12-05 10:49 UTC, rbikar commented
jenkins CI seems to be still broken

2022-12-05 10:51 UTC, merged