able to use the pulp cert and key to auth
release-engineering/ubi-population-tool pull request #216
Opened 2023-06-19 07:26 UTC by LinglingXiang

able to use the pulp cert and key to auth

2023-06-19 07:39 UTC, LinglingXiang commented
@rbikar ,please help review, thanks

2023-06-19 08:33 UTC, rbikar requested changes

2023-06-19 08:33 UTC, rbikar commented on tests/integration/test_association.py
> +    if PULP_CERT_PATH is not None:
Can you de-duplicate the code please?
Check this out for one of possible variant:
https://github.com/release-engineering/ubi-manifest/blob/62f3e4d55ee61f389b69ad9efb6b35c726092bf2/ubi_manifest/worker/tasks/depsolver/utils.py#L21

2023-06-20 03:19 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    if PULP_CERT_PATH is not None:
changed.

2023-06-20 03:21 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    if PULP_CERT_PATH is None:
hi Robert, i didn't change it as in future, i want to replace to use the same pubtools.pulplib client as above.

2023-06-20 03:21 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    if PULP_CERT_PATH is not None:
changed.

2023-06-20 03:21 UTC, LinglingXiang commented on tests/integration/test_association.py
>          auth = (PULP_CERT_PATH,)
changed

2023-06-20 12:53 UTC, rbikar commented
run tests

2023-06-21 06:34 UTC, LinglingXiang commented
hi Robert, the #175 failed as mongo service on pulp server, so we can see the db restore failed on the job .after fix the service of mongo, the #176 is pass

2023-06-21 08:44 UTC, rbikar approved these changes

2023-06-21 08:45 UTC, merged