Replace usage of _pulp_client with pubtools-pulplib [RHELDST-141]
release-engineering/ubi-population-tool pull request #223
Opened 2024-03-14 17:10 UTC by negillett

This commit removes the library's native _pulp_client ("legacy") and replaces it with usage of pubtools-pulplib methods for associating and unassociating content.

Additionally, PulpActions were replaced with simple abstractions for grouping content to be associated/unassociated.

Tests were removed/edited as necessary.

2024-03-14 17:12 UTC, negillett commented
run tests

2024-03-14 19:20 UTC, negillett commented
run tests

2024-03-14 19:57 UTC, negillett commented
run tests

2024-03-15 16:32 UTC, negillett commented
run tests

2024-03-15 20:20 UTC, negillett commented
run tests

2024-03-15 21:23 UTC, negillett commented
run tests

2024-03-15 21:35 UTC, negillett commented
run tests

2024-03-15 21:41 UTC, negillett commented
run tests

2024-03-15 21:47 UTC, negillett commented
I'm at a total loss as to why we're seeing error 111 on '/api/v1/manifest'. I've touched nothing in the ubi client.

2024-03-18 08:55 UTC, rbikar commented
> I'm at a total loss as to why we're seeing error 111 on '/api/v1/manifest'. I've touched nothing in the ubi client. Any ideas, @rbikar?

I think the ubi-manifest service in the test env was in a bad shape, I re-ran tests and they passed OK.

2024-03-18 09:33 UTC, rbikar requested changes

2024-03-18 09:33 UTC, rbikar commented on ubipop/__init__.py
> +                unit_crit = Criteria.with_unit_type(RpmUnit)
`unit_crit` is loop invariant, you can set this outside of the loop. It may need a little redesign of this method. You can e.g. pass the class (e.g. `RpmUnit`)  via argument.

2024-03-18 09:33 UTC, rbikar commented on ubipop/__init__.py
> +    def _criteria_for_units(self, units, unit_type):
Do you think you can some batching mechanism for criteria? During bigger events like GA, criteria tend to be pretty big (especially for rpms) so it would be nice to have associations or unassociations split into batches.

2024-03-18 09:33 UTC, rbikar commented on ubipop/__init__.py
> +        assert unit_crit
I don't think those asserts are needed, this code is not public API, so the code + tests should ensure that it works properly.

Btw, currently it won't say much to the user if it fails on this.

2024-03-18 09:33 UTC, rbikar commented on ubipop/__init__.py
> +            ft.result()
This probably can a bit re-written.
Inside the the loop, the future `ft` is already completed because we loop using `as_completed`.

I'd suggest either to use just `wait(futures)` ,  or maybe also add some logging that would tell us what copy/removal of content was completed, e.g. via `future.add_done_callback(some_logging_function)`

2024-03-18 15:44 UTC, negillett commented on ubipop/__init__.py
> +                unit_crit = Criteria.with_unit_type(RpmUnit)
Yeah, accepting the unit object was my initial approach but I thought it'd make the function easier to use if it accepted a string instead. You're right that this is needlessly reassigning though so I'll improve that.

2024-03-18 15:45 UTC, negillett commented on ubipop/__init__.py
> +        assert unit_crit
This was probably leftover from debugging. Thanks for pointing it out!

2024-03-18 16:35 UTC, negillett commented on ubipop/__init__.py
> +            ft.result()
Ah, okay. I think we'll just loop fts for `result` then. Using `wait` would force us to support the `not_done` cases, and there doesn't seem to be much benefit there. Adding a logging callback would be nice but I don't think it would make sense here, maybe upon future creation.

2024-03-18 17:13 UTC, negillett commented on ubipop/__init__.py
> +            ft.result()
Decided against implementing a log callback as there's no useful info available at the future level such as the function name or arguments supplied. We can log future results in other ways if we really want to do that.

2024-03-18 22:05 UTC, negillett commented on ubipop/__init__.py
> +    def _criteria_for_units(self, units, unit_type):
Assuming you mean something like returning a list of criteria rather than a single criteria for all the given units, e.g., a set of rpm criteria, modulemd criteria, and modulemd_defaults criteria. Yeah, that should be rather easy.

2024-03-18 22:50 UTC, negillett commented on tests/test_ubipop.py
Added this bit to check the content on the published repos but the results seem odd to me. The rpm isn't published  and debug and source repos are empty. Is that intended here, @rbikar?

2024-03-19 09:34 UTC, rbikar commented on ubipop/__init__.py
> +            ft.result()
yeah, no problem. It's not in the scope of the issue.

2024-03-19 09:37 UTC, rbikar commented on ubipop/__init__.py
> +    def _criteria_for_units(self, units, unit_type):
It can be problematic especially with RPMs, returning criteria e.g. for 100 units and running copy/remove and then another 100 units would be useful.

2024-03-19 10:04 UTC, rbikar commented on ubipop/__init__.py
> +                ft.result
this doesn't look OK.
You need to call the result method:
```
ft.result()
```

2024-03-19 14:35 UTC, negillett commented on ubipop/__init__.py
> +                ft.result
Good catch. Ty!

2024-03-19 14:39 UTC, negillett commented on tests/test_ubipop.py
Thanks for confirming, I'll try to track down that rpm unit (still missing after url mocks removed).

2024-03-19 14:54 UTC, negillett commented on ubipop/__init__.py
> +    def _criteria_for_units(self, units, unit_type):
Oh, I see. I've split the criteria by unit but I can work batch size limit into the un/associations methods.

2024-03-19 18:19 UTC, negillett commented on tests/test_ubipop.py
Update:
Added some logs to see what was going on, looks like pulp_client.copy_content isn't handling RpmUnits properly.

> Got an RPM unit: RpmUnit(src_repo_id='input_binary', dst_repo_id='ubi_binary', filename='golang-2.a.x86_64.rpm')
Made criteria for RPM: ((content_type_id IN ['rpm', 'srpm']) AND filename=='golang-2.a.x86_64.rpm')
Did associations: [Task(id='e3e70682-c209-4cac-629f-6fbed82c07cd', completed=True, succeeded=True, tags=[], repo_id='input_binary', units=[ModulemdUnit(name='test_md', stream='s', version=200, context='c', arch='x86_64')], units_data=[]), Task(id='82e2e662-f728-b4fa-4248-5e3a0a5d2f34', completed=True, succeeded=True, tags=[], repo_id='input_binary', units=[], units_data=[])]

Continuing investigation

2024-03-19 18:22 UTC, negillett commented on tests/test_ubipop.py
Or maybe there's some reason filename isn't findable on fake_pulp.

2024-03-20 16:59 UTC, rbikar commented on tests/test_ubipop.py
I found the culprit, the fake_pulp.copy_content() by default requires signing_key set on Rpm units.
So e.g. setting `signing_key="xxxx"` on testing RPM unit will fix the problem.

2024-03-20 18:58 UTC, negillett commented on tests/test_ubipop.py
Oh, nice. Thanks, @rbikar!

2024-03-20 18:59 UTC, negillett commented
run tests

2024-03-20 19:12 UTC, negillett commented on tests/test_ubipop.py
@rbikar, I submitted https://github.com/release-engineering/pubtools-pulplib/pull/219 too. No reason to behave differently here.

2024-03-20 19:21 UTC, negillett commented
run tests

2024-03-20 19:50 UTC, negillett commented
run tests

2024-03-21 07:15 UTC, rbikar requested changes

2024-03-21 07:15 UTC, rbikar commented on tests/test_ubipop.py
> +        repo_content = repo.search_content().result().data
This looks a bit suspicious,
I believe you can do just `repo_content = repo.search_content()` and iterate over it.
Or you can get the content with convenient methods:
https://release-engineering.github.io/pubtools-pulplib/api/pulpcore.html#pubtools.pulplib.Repository.rpm_content and others

2024-03-21 07:15 UTC, rbikar commented on ubipop/__init__.py
> +    def _batch_units(self, units):
Can you please add test that actually will use more than one batch?

2024-03-21 07:15 UTC, rbikar commented on ubipop/__init__.py
> +            if unit_type is RpmUnit:
can you change this multiple ifs section into if-elif style?

2024-03-21 07:15 UTC, rbikar commented on tests/test_ubipop.py
> +        signing_key="xxxx",
minor: the signing_key can hold a bit better value like `test_signing_key`

2024-03-21 07:15 UTC, rbikar commented on tests/test_ubipop.py
> -    expected_published_repo_ids = set(["ubi_binary", "ubi_debug", "ubi_source"])
In production we already stopped publishing content via this tool, but isn't this part of test still valid?

2024-03-21 14:50 UTC, negillett commented on tests/test_ubipop.py
> +        signing_key="xxxx",
I haven't seen an existing variable yet and there doesn't seem to be much benefit to creating one since the value isn't being used. I can make the key look a little more realistic though I suppose.

2024-03-21 14:53 UTC, negillett commented on ubipop/__init__.py
> +            if unit_type is RpmUnit:
Yeah, thanks. Not sure what started this habit but there's no use for the extra if checks here.

2024-03-21 14:56 UTC, negillett commented on ubipop/__init__.py
> +                    src_obj = self.pulp_client.get_repository(a.get_repo(src_repo).id)
Yeah, that's right. Thanks

2024-03-21 14:57 UTC, negillett commented on ubipop/_utils.py
> +    def src_repo_to_unit_map(self):
Done!

2024-03-21 15:01 UTC, negillett commented on ubipop/__init__.py
> +    def _do_associations(self, associations):
Done!

2024-03-21 15:05 UTC, negillett commented on ubipop/__init__.py
> +        for ft in association_fts:
Done!
Wasn't sure how crucial it was for rpm+modulemd units to be done together.

2024-03-21 15:17 UTC, negillett commented on tests/test_ubipop.py
> +        repo_content = repo.search_content().result().data
Yeah, seems the result call isn't necessary anymore (it was at one point, unsure why now).
I was hesitant about using the *_content repo attributes since they each call search_content, but it does look a lot better in the test.

2024-03-21 15:48 UTC, negillett commented on ubipop/__init__.py
> +    def _batch_units(self, units):
Creating another large test with 100s of unit objects sounds expensive for a unit test. Something of that scale should be captured in the integration tests already, right?

However, I did move this method to utilities and added a unit test for it.

2024-03-21 15:55 UTC, negillett commented
run tests

2024-03-22 14:23 UTC, negillett commented
run tests

2024-03-22 14:34 UTC, negillett commented
run tests

2024-03-22 14:39 UTC, negillett commented
run tests

2024-03-22 15:55 UTC, negillett commented
run tests

2024-03-25 13:45 UTC, negillett commented
run tests

2024-03-25 14:50 UTC, negillett commented
@rbikar, is ubi-manifest okay? I keep seeing connection errors (Connection aborted) for ubi-manifest task in `test_ubipop_not_filter_module_rpm_with_different_version`.

However, I think the test is failing because it's expected "common [d]" in the module profile but the profiles are "rhel" and "common". Should that "[d]" really be expected?

2024-03-26 16:49 UTC, negillett commented on tests/integration/test_association.py
> +        "common" in mod_profile
"rhel" and "common" are present, neither has this "[d]" mark.
@rbikar, I'm assuming it's meant to label the default profile but I don't see a mechanism for that in this repo which may have changed and wonder if that's still used/expected.

2024-03-26 16:50 UTC, negillett commented
run tests

2024-03-26 17:21 UTC, rbikar commented on tests/integration/test_association.py
> +        "common" in mod_profile
Yeah, the `[d]` should mean that the profile is the default one.
It's possible that something changed either in the testing modulemd/modulemd_defaults content or in yum/dnf tooling.

And for ubi-manifest health - I don't manage/check this testing instance, you would to check with our QEs.

2024-03-26 19:40 UTC, negillett commented
run tests

2024-03-26 22:06 UTC, negillett commented
run tests

2024-03-27 18:29 UTC, negillett commented
run tests

2024-03-27 19:13 UTC, negillett commented
run tests

2024-03-28 14:35 UTC, negillett commented
@rbikar, @rohanpm, this is ready for review.
I'm still unsure why some modulemd profiles no longer contain "[d]" to signal default but I don't believe the change was introduced here (it was only ever present in the integration tests). It could be a difference between rhel7 and rhel8 content--this is a key difference between the two integration tests that asserted the presence of the mark.

2024-03-28 15:09 UTC, rbikar commented
> @rbikar, @rohanpm, this is ready for review. I'm still unsure why some modulemd profiles no longer contain "[d]" to signal default but I don't believe the change was introduced here (it was only ever present in the integration tests). It could be a difference between rhel7 and rhel8 content--this is a key difference between the two integration tests that asserted the presence of the mark.

In realistic usage the ubi7 shouldn't have any modules (but I guess in test the situation can be different).

Anyway you need to examine `modulemd_defaults` units in the test instance of rhsm-pulp before and after the test.

I checked current real ubi8 image and e.g. for perl module I get this:
Output of `dnf module list` (I was unable to copy this output as it shows on my terminal)
```
perl                 5.24       common [d Practical Extraction and Report Language                                                                                                                                                             
                                ], minima 
                                l         
perl                 5.26 [d]   common [d Practical Extraction and Report Language                                                                                                                                                             
                                ], minima 
                                l         
perl                 5.30       common [d Practical Extraction and Report Language                                                                                                                                                             
                                ], minima 
                                l         
perl                 5.32       common [d Practical Extraction and Report Language                                                                                                                                                             
                                ], minima 
                                l   
``` 
and corresponding `modulemd_defaults` unit in production rhsm-pulp data:
(Maybe the testing code reads wrongly the output as in terminal the formatting doesn't look very nice)
```
...
            "name": "perl",
            "profiles": {
                "5.24": [
                    "common"
                ],
                "5.26": [
                    "common"
                ],
                "5.30": [
                    "common"
                ],
                "5.32": [
                    "common"
                ]
            },
            "pulp_user_metadata": {},
            "repo_id": "ubi-8-for-x86_64-appstream-rpms__8",
            "stream": "5.26"
        },
...
```
which say 2 things:
* what profile is default for which stream
* what stream is default for the module

so it should be dependent on the data in pulp only, can you double-check the removal and copy of modulemd_defaults units? There might some subtle bug (or the formatting problem as I mentioned above).

2024-03-28 20:45 UTC, negillett commented
run tests

2024-03-28 22:11 UTC, negillett commented
"common [d]" is showing up now for that one tests 🤷🏻

2024-03-28 22:12 UTC, negillett commented
run tests

2024-04-01 14:38 UTC, negillett commented
@rohanpm @rbikar ptal

2024-04-05 14:32 UTC, merged