Authenticate session with kerberos
release-engineering/ubi-population-tool pull request #234
Opened 2024-07-04 09:05 UTC by drepelov

To access ubi-manifest server, requests session now needs to be authenticated using kerberos.

2024-07-09 06:40 UTC, drepelov commented
run tests

2024-07-09 07:30 UTC, rbikar requested changes

2024-07-11 10:46 UTC, rbikar commented
run tests

2024-07-11 10:48 UTC, rbikar commented
@drepelov 

As agreed, taking overt this PR.
I've added a couple of things that should good enough for further deployment with kerb. auth.

I don't expect jenkins tests to pass.

2024-07-12 12:49 UTC, merged