Add the command to let pub client to do the publish [RHELDST-25071]
release-engineering/ubi-population-tool pull request #237
Opened 2024-08-30 07:53 UTC by LinglingXiang

1.let pub client to do the publish

2024-09-04 02:31 UTC, LinglingXiang commented
@drepelov @rbikar , please help review it, thanks

2024-09-05 02:22 UTC, LinglingXiang commented
@drepelov @rbikar , the format issue fixed,  please help review it, thanks

2024-09-06 07:46 UTC, rbikar requested changes

2024-09-06 07:46 UTC, rbikar commented on tests/integration/test_association.py
> +            raise Exception(ret)
Not a big deal, it may be better to raise more specific exception.

2024-09-06 07:46 UTC, rbikar commented on tests/integration/test_association.py
> +            print("The publish is not successful, so please check it first")
seems like you sometimes use `print` and sometimes `logging` it would good to use only one variant, I guess.

2024-09-06 07:46 UTC, rbikar commented on tests/integration/test_association.py
> +    except subprocess.CalledProcessError as ex:
you probably want to re-raise this exception, otherwise tests will continue with unpublished repos.

2024-09-09 01:38 UTC, LinglingXiang commented on tests/integration/test_association.py
> +            print("The publish is not successful, so please check it first")
fixed

2024-09-09 01:38 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    except subprocess.CalledProcessError as ex:
fixed

2024-09-09 01:38 UTC, LinglingXiang commented on tests/integration/test_association.py
> +            raise Exception(ret)
fixed

2024-09-09 13:23 UTC, rbikar approved these changes

2024-09-09 13:23 UTC, merged