Fix the failture of ubipop for rhel7
release-engineering/ubi-population-tool pull request #240
Opened 2024-09-23 02:37 UTC by LinglingXiang

After the slave update from fedora 38 to fedora 40, the module query list return empty string, so remove the empty string and make the test case is pass.

2024-09-26 06:52 UTC, LinglingXiang commented
@rbikar @drepelov , could you help review it, thanks

2024-09-30 09:22 UTC, rbikar requested changes

2024-09-30 09:22 UTC, rbikar commented on tests/integration/test_association.py
> +    modulemds = query_repo_modules(None, "ubi", rpm_repo_url)
you do another unnecessary call for the second time a few lines later, can you please refactor this so it does only one call and then filters received data in ` query_repo_modules` ?

2024-09-30 09:22 UTC, rbikar commented on tests/integration/test_association.py
> +    while "" in modulemds:
can you move this to `query_repo_modules` function? This filtering shouldn't be part of test. You can likely need this operation for other tests in future, so it's better to be done once in the function.

2024-09-30 09:22 UTC, rbikar commented on tests/integration/test_association.py
> +        "common" in mod_profile
Did really the output changed for default modules? Or do we have rather problem in testing data or ubi-population-tool?

2024-10-09 02:17 UTC, LinglingXiang commented on tests/integration/test_association.py
> +        "common" in mod_profile
hi Robert, the cause is the same as previous one query_repo_modules. After some investigation,  the method works well in fedora38, in fedora 40, it will return in wrong format
Name      Stream                Profiles                   Summary             
httpd     2.4 [d]               common [ Apache HTTP Server  
                                d], defa                     
                                ult, dev                     
                                el   
if i update the yum update util-linux in fedora 40, the method can return mormally. 
In summary, nothing wrong in this method, but something problem in os.
so i will change the fedora 40 slave script instead of changing the method

2024-10-09 02:21 UTC, LinglingXiang commented on tests/integration/test_association.py
> +    while "" in modulemds:
the same as below comments, i will close the merge request.
and submit a patch for changing the slave

2024-10-09 02:21 UTC, closed without merging