Authenticate with requests-gssapi [RHELDST-25389]
release-engineering/ubi-population-tool pull request #242
Opened 2024-11-21 07:49 UTC by Gdetrane

Migrate deprecated requests_kerberos library to requests_gssapi for kerberos authentication.

2024-11-21 07:50 UTC, Gdetrane commented
@drepelov ptal

2024-11-21 09:17 UTC, rbikar requested changes

2024-11-21 09:17 UTC, rbikar commented on ubipop/ubi_manifest_client/client.py
> +                os.environ["KRB5_CLIENT_PRINCIPAL"] = self.krb_principal
This https://github.com/pythongssapi/requests-gssapi?tab=readme-ov-file#explicit-principal  says that we can set it more cleanly via passing  proper object to `creds` argument in `HTTPSPNEGOAuth()`

Setting it via env var looks a bit hacky to me and is not mentioned in those docs.

2024-11-21 09:17 UTC, rbikar commented on ubipop/ubi_manifest_client/client.py
> -                    force_preemptive=True,
I believe we still need to enforce preemptive initiation of auth, in gssapi lib it can be done via `opportunistic_auth=True` , if I get it right.

check [docs](https://github.com/pythongssapi/requests-gssapi?tab=readme-ov-file#opportunistic-authentication)

2024-11-27 09:20 UTC, Gdetrane commented
run tests

2024-11-28 10:32 UTC, drepelov commented
run tests

2024-11-28 10:47 UTC, drepelov commented
run tests

2024-12-02 06:48 UTC, drepelov commented
run tests

2024-12-04 11:19 UTC, rbikar approved these changes

2024-12-04 11:19 UTC, merged