Retire native ubipop publishing [RHELDST-25072]
release-engineering/ubi-population-tool pull request #243
Opened 2024-11-29 15:46 UTC by Gdetrane

+ Remove `cdn.py` module containing the `Publisher` class
+ Remove the *UBIPOP_SKIP_PUBLISH* env variable used for switching between publishers
+ Removed the *publisher* option for classes using it

2024-12-04 11:20 UTC, rbikar commented
run tests

2024-12-04 11:25 UTC, rbikar requested changes
Almost OK, please rebase (it should likely fix the lock file)

2024-12-04 11:25 UTC, rbikar commented on ubipop/__init__.py
> +            if os.environ.get("UBIPOP_SKIP_PUBLISH"):
I don't think we need to warn. It's never been documented anywhere.

2024-12-04 11:25 UTC, rbikar commented on poetry.lock
Although it's not a big deal, but it looks that changes in the lock file are not relevant to the PR.  At least I don't see any change in direct deps right now in PR.

2024-12-04 12:10 UTC, Gdetrane commented on ubipop/__init__.py
> +            if os.environ.get("UBIPOP_SKIP_PUBLISH"):
I felt I was probably being too verbose with an unnecessary warning, my fear was that some people might try to set the variable thinking the old implementation is still there and see no effects, but I guess if someone knows about it in the first place, this should not be a concern.
I'll remove it right away

2024-12-04 13:16 UTC, Gdetrane commented on poetry.lock
I was having issues with the tests and regenerating the lock file fixed them, I wasn't sure whether to commit it or not.
I rebased this fork's branch on upstream/master on the last push, that does not seem to resolve the conflict though, maybe I didn't do it properly with the incoming changed during rebase?
I'm still in doubt about the lock file itself and whether I should've committed in the first place, because technically without that change the test suite wouldn't even install for all envs if I remember correctly

2024-12-04 13:21 UTC, rbikar commented on poetry.lock
Unfortunately we haven't set up automated deps update (and update to lock file), but if you can, can you please create extra PR with update to all deps and then we can rebase this PR.

2024-12-04 13:22 UTC, rbikar commented on poetry.lock
Conflict there is likely because of https://github.com/release-engineering/ubi-population-tool/pull/242 - which had new deps.

2024-12-04 13:27 UTC, Gdetrane commented on poetry.lock
Oh right, we moved from requests-kerberos to requests-gssapi explicitly, but I'm surprised that the different pyproject.toml did not show up during rebase (I did it after #242 was merged)?

Anyways, would you mean simply having a fork from master explicitly with a new lock file generated by the updated pyproject.toml? That one should already be in master so it shouldn't be too much of an effort

2024-12-05 14:52 UTC, rbikar commented
@Gdetrane 
I am not sure why diff still shows changes in lock file and pyproject.toml...

2024-12-05 15:06 UTC, Gdetrane commented
@rbikar should be okay now

2024-12-05 15:13 UTC, rbikar commented
run tests

2024-12-05 15:14 UTC, rbikar commented
@Gdetrane 
yep, diff is OK now, but can you check the code coverage report? It seems like we get a bit lower number.

2024-12-06 09:39 UTC, rbikar approved these changes

2024-12-06 09:39 UTC, merged